name = "nthumods-auth"
main = "src/index.ts"
compatibility_date = "2025-03-27"
routes = [
  { pattern = "auth.nthumods.com", custom_domain = true }
]
minify = true
assets = { directory = "src/pages/output.css" }

[dev]
port = 5002
local_protocol = "http"

[observability]
enabled = true
head_sampling_rate = 1
